version: "3.9"

services:
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    command: start --user root --pass root file://data/surrealdb.db
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SURREAL_URL=ws://surrealdb:8000/rpc
      - SURREAL_USER=root
      - SURREAL_PASS=root
      - SURREAL_NS=adaptive_learning
      - SURREAL_DB=learning_platform
      - OPENROUTER_API_KEY=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
      - JWT_SECRET=fb7cabb905a70294be229de37d88365b6cc6a56095a23f399d159abef55fee04
      - BASE_STORAGE_DIR=/app/storage
      - CHROMA_PATH=/app/chroma_db
    depends_on:
      - surrealdb
    volumes:
      - ./backend/storage:/app/storage
      - ./chroma_db:/app/chroma_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    depends_on:
      - backend

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=adaptive_learning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  surreal_data:
  postgres_data: